version: '3.1'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql:mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        container_name: php-fpm
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www

        links:
            - mysql:mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        tty: true
        container_name: php-cli

    mysql:
        image : mysql:latest
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
        ports:
            - "3306:3306"

    redis:
        image: redis:7.2
        ports:
            - "6379:6379"

    node:
        build:
            context: ./
            dockerfile: docker/node.docker
        volumes:
            - ./:/var/www
        tty: true
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1

